//
//  EditProfileViewController.swift
//  CleanSwiftDemo
//
//  Created by Tony Mak on 06/03/2020.
//  Copyright (c) 2020 Tony Mak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileDisplayLogic: class {
    func displaySomething(viewModel: EditProfile.Something.ViewModel)
}

class EditProfileViewController: UIViewController, EditProfileDisplayLogic {
    var interactor: EditProfileBusinessLogic?
    var router: (NSObjectProtocol & EditProfileRoutingLogic & EditProfileDataPassing)?
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
  
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    func doSomething() {
        let request = EditProfile.Something.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: EditProfile.Something.ViewModel) {
    }
}
