//
//  EditProfilePresenter.swift
//  CleanSwiftDemo
//
//  Created by Tony Mak on 06/03/2020.
//  Copyright (c) 2020 Tony Mak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfilePresentationLogic {
    func presentSomething(response: EditProfile.Something.Response)
}

class EditProfilePresenter: EditProfilePresentationLogic {
    weak var viewController: EditProfileDisplayLogic?
  
    func presentSomething(response: EditProfile.Something.Response) {
        let viewModel = EditProfile.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
