//
//  ProfileModels.swift
//  CleanSwiftDemo
//
//  Created by Tony Mak on 06/03/2020.
//  Copyright (c) 2020 Tony Mak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
  enum InitView {
    struct Request {
    }
    
    struct Response {
        let user: User
    }
    
    struct ViewModel {
        let navTitle: String
        let name: String
        let profileList: [ViewModelProfileItem]
    }
    
    struct ViewModelProfileItem: Equatable {
        let title: String
        let value: String
    }
  }
}
