//
//  ProfileInteractor.swift
//  CleanSwiftDemo
//
//  Created by Tony Mak on 06/03/2020.
//  Copyright (c) 2020 Tony Mak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func requestInitView(request: Profile.InitView.Request)
}

protocol ProfileDataStore {
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    
    var user: User? = nil

    func requestInitView(request: Profile.InitView.Request) {
        //Demo hardcode
        user = User(
            id: 1,
            memberNo: "123456",
            firstName: "Tony",
            lastName: "Mak",
            email: "abc@email.com",
            phone: "99999999",
            address: "Hong Kong"
        )
        let response = Profile.InitView.Response(user: user!)
        self.presenter?.presentInitView(response: response)
    }
}
