//
//  ProfilePresenter.swift
//  CleanSwiftDemo
//
//  Created by Tony Mak on 06/03/2020.
//  Copyright (c) 2020 Tony Mak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentInitView(response: Profile.InitView.Response)
}

class ProfilePresenter: ProfilePresentationLogic {
    weak var viewController: ProfileDisplayLogic?
    
    func presentInitView(response: Profile.InitView.Response) {
        let user = response.user
        let userName = "\(user.firstName) \(user.lastName)"
        var profileList: [Profile.InitView.ViewModelProfileItem] = []
        
        let profileItem1 = Profile.InitView.ViewModelProfileItem(title: "Member No.", value: user.memberNo)
        let profileItem2 = Profile.InitView.ViewModelProfileItem(title: "Email", value: user.email)
        let profileItem3 = Profile.InitView.ViewModelProfileItem(title: "Phone", value: user.phone)
        let profileItem4 = Profile.InitView.ViewModelProfileItem(title: "Address", value: user.address)
        
        profileList.append(profileItem1)
        profileList.append(profileItem2)
        profileList.append(profileItem3)
        profileList.append(profileItem4)
        
        let viewModel = Profile.InitView.ViewModel(navTitle: "Profile", name: userName, profileList: profileList)
        viewController?.displayInitView(viewModel: viewModel)
    }
}
